#! /bin/sh
#
#  ██████╗ ███████╗██████╗ ██╗    ██╗███╗   ███╗██████╗  ██████╗
#  ██╔══██╗██╔════╝██╔══██╗██║    ██║████╗ ████║██╔══██╗██╔════╝
#  ██████╔╝███████╗██████╔╝██║ █╗ ██║██╔████╔██║██████╔╝██║     
#  ██╔══██╗╚════██║██╔═══╝ ██║███╗██║██║╚██╔╝██║██╔══██╗██║     
#  ██████╔╝███████║██║     ╚███╔███╔╝██║ ╚═╝ ██║██║  ██║╚██████╗
#  ╚═════╝ ╚══════╝╚═╝      ╚══╝╚══╝ ╚═╝     ╚═╝╚═╝  ╚═╝ ╚═════╝
# 

PATH="$HOME/.config/scripts:$PATH" 
pgrep -x sxhkd > /dev/null || sxhkd &

xrandr --output HDMI1 --mode 1920x1080 --primary

if [[ $(xrandr -q |grep 'HDMI2 connected') ]]; then 
  xrandr --output HDMI2 --mode 1920x1080 --below HDMI1
fi

polkit-dumb-agent &
mpd &
udiskie &
picom &
polybar &
nitrogen --restore &
dunst &
notify-send -u low "󰯉  welcome 󰯉 " &
systemctl --user start wireplumber pipewire-pulse &
sxhkd &
udisksctl mount -b /dev/sda1 &
setxkbmap -option "ctrl:swap_ralt_rctl" &
setxkbmap -option "caps:escape_shifted_capslock" &


bspc monitor HDMI1 -d   󰈹   ﭮ 
bspc monitor HDMI2 -d 󰯉   


bspc config border_width         0
bspc config window_gap          10 

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a inkscape desktop="^1" follow=on
bspc rule -a firefox desktop='^3' follow=on
bspc rule -a discord desktop='^4' follow=on

