#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

xrandr --output HDMI-1 --mode 1920x1080 --primary

if [[ $(xrandr -q |grep 'HDMI-2 connected') ]]; then 
  xrandr --output HDMI-2 --mode 1920x1080 --below HDMI-1
fi

nitrogen --restore &
sxhkd &
picom &
polybar &
/usr/bin/polkit-dumb-agent &


bspc monitor HDMI-1 -d   󰈹   ﭮ 
bspc monitor HDMI-2 -d 󰯉   


bspc config border_width         0
bspc config window_gap 9


bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^1' state=floating follow=on
bspc rule -a firefox desktop='^3' follow=on
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
